### ISSUE TITLE
grande demais para mostrar

### ISSUE THREAD

**Issue by akol67** [InTRA-USP/IntraSOM#1]
exemplos/exemplos_doc.ipynb não abre pois é "muito grande para mostrar". Algum problema, de fato, com o arquivo ?

**Comment by akol67** [comment]
fazendo o download é a unica solução

**Comment by rafaelgioria** [comment]
@rodiegeology 
Podemos adicionar uma anotação avisando o tamanho grande impede abertura diretamente no github?

Indicar em:
https://github.com/InTRA-USP/IntraSOM/tree/pt_br#documenta%C3%A7%C3%A3o-e-exemplos

E com um README.md em:
https://github.com/InTRA-USP/IntraSOM/tree/pt_br/exemplos

E replicar no branch em ingles.

**Comment by rodiegeology** [comment]
@rafaelgioria @akol67 Eu coloquei o aviso no Readme: "Note: This notebook is not loaded via GitHub due to its size, but it can be accessed through any IDE that supports Jupyter Notebooks.". E estou nesse momento avaliando se consigo colocar no Binder ou no Google Colab para acesso online, estou trabalhando em colocar as referencias às imagens por link e não localmente para carregarem em qualquer IDE de Jupyter Notebook.

**Comment by rafaelgioria** [comment]
sugestão em teste:
manter um notebook sem as saídas armazenadas. ver [PR#5](https://github.com/InTRA-USP/IntraSOM/pull/5).
